# Generated by Django 2.0.3 on 2018-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('to_emails', models.TextField(blank=True, default='')),
                ('subject', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-creation_date'],
            },
        ),
    ]
