# Generated by Django 2.0.3 on 2018-03-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Уникальное имя для обращения в шаблоне, лучше использовать латиницу без пробелов', max_length=255, unique=True, verbose_name='ключ')),
                ('content', models.TextField(help_text='Содержимое блока', verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название партнерки', max_length=255, verbose_name='Партнерка')),
            ],
            options={
                'verbose_name': 'Партнерка',
                'verbose_name_plural': 'Партнерки',
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='partner',
            field=models.ForeignKey(help_text='Название партнерки', on_delete=django.db.models.deletion.CASCADE, to='advert.Partner', verbose_name='Партнерка'),
        ),
    ]
