# Generated by Django 2.0.3 on 2018-03-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0002_auto_20180330_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'proxy': True,
                'indexes': [],
            },
            bases=('blogs.post',),
        ),
    ]
