# Generated by Django 2.0.3 on 2018-03-30 22:11

import ckeditor_uploader.fields
from django.db import migrations, models

import apps.blogs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликован?')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (meta тег)')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова (meta тег)')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (meta тег)')),
                ('seo_author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор (meta тег)')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('categorytype', models.PositiveSmallIntegerField(choices=[(0, 'Обычная категория'), (1, 'Категория вопроса'), (2, 'Категория новости'), (3, 'Категория практики')], db_index=True, default=0, verbose_name='Тип категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Класс картинки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликован?')),
                ('author_username', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Комментарий')),
                ('is_spam', models.BooleanField(default=False, verbose_name='Спам?')),
                ('rate', models.IntegerField(default=0, verbose_name='Кол-во лайков')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-creation_date',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликован?')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (meta тег)')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова (meta тег)')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (meta тег)')),
                ('seo_author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор (meta тег)')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('announcement', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Анонс')),
                ('post', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья')),
                ('view_count', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('rate', models.IntegerField(default=0, verbose_name='Кол-во лайков')),
                ('num_comments', models.IntegerField(default=0, verbose_name='Кол-во комментариев')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/posts/', verbose_name='Главная картинка')),
                ('notes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Notes', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-publication_date',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
                'ordering': ('-creation_date',),
            },
        ),
    ]
