# Generated by Django 2.0.3 on 2018-03-31 05:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180330_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
