# Generated by Django 2.0.3 on 2018-03-30 22:11

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=255, verbose_name='Контактный email')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('pagetype', models.PositiveSmallIntegerField(choices=[(0, 'Рекламодателям'), (1, 'Правила и авторские права'), (3, 'Контакт с администрацией'), (4, 'Авторизация'), (5, 'Регистрация'), (6, 'Изменить пароль'), (19, 'Сбросить пароль'), (7, 'О нас'), (8, 'Предложить свою статью'), (9, 'Задать вопрос'), (10, 'Знаете ли вы'), (11, 'Анекдот дня'), (12, 'Комментируемые статьи'), (13, 'Бесплатная помощь'), (14, 'Новые интересные статьи на портале'), (15, 'Практические советы'), (16, 'Реклама справа'), (20, 'Реклама в статье'), (17, 'Реклама сверху'), (22, 'Реклама посередине'), (18, 'Новости'), (21, 'Опрос')], unique=True, verbose_name='Тип страницы')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('data', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='PollItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('rate', models.IntegerField(default=0, verbose_name='Кол-во за')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='PollMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.Material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал опроса',
                'verbose_name_plural': 'Материалы опросов',
            },
        ),
        migrations.CreateModel(
            name='PostMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('sort_publication_date', models.BooleanField(default=True, verbose_name='Сортировать по дате публикации')),
                ('sort_comments_count', models.BooleanField(default=False, verbose_name='Сортировать по кол-ву комментариев')),
                ('sort_views_count', models.BooleanField(default=False, verbose_name='Сортировать по кол-ву просмотров')),
                ('count', models.PositiveIntegerField(default=10, verbose_name='Кол-во статей')),
                ('filter_catgories', models.ManyToManyField(blank=True, to='blogs.Category', verbose_name='Фильтровать по категориям')),
                ('filter_tags', models.ManyToManyField(blank=True, to='blogs.Tag', verbose_name='Фильтровать по меткам')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.Material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал поста',
                'verbose_name_plural': 'Материалы постов',
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_author', models.CharField(blank=True, max_length=255, null=True)),
                ('stat_liveinternet', models.TextField(blank=True, null=True)),
                ('stat_yandex', models.TextField(blank=True, null=True)),
                ('stat_google', models.TextField(blank=True, null=True)),
                ('yandex_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('google_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('important_message', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sites.Site')),
            ],
            options={
                'verbose_name': 'Профайл сайта',
                'verbose_name_plural': 'Профайлы сайтов',
            },
        ),
        migrations.CreateModel(
            name='TextMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_random_show', models.BooleanField(default=True, verbose_name='Показывать рандомно')),
                ('is_day_show', models.BooleanField(default=False, verbose_name='Показывать рандомно по дням')),
                ('separator', models.CharField(default='<cut/>', max_length=255, verbose_name='Разделитель')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.Material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал текста',
                'verbose_name_plural': 'Материалы текстов',
            },
        ),
        migrations.AddField(
            model_name='pollitem',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.PollMaterial', verbose_name='Опрос'),
        ),
    ]
