# Generated by Django 2.0.3 on 2018-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (meta тег)')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова (meta тег)')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (meta тег)')),
                ('seo_author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор (meta тег)')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликован?')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Тип страницы')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
