# Generated by Django 2.0.3 on 2018-03-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_seopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmaterial',
            name='filter_catgories',
        ),
        migrations.RemoveField(
            model_name='postmaterial',
            name='filter_tags',
        ),
        migrations.RemoveField(
            model_name='postmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='site',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='material',
        ),
        migrations.AlterModelOptions(
            name='pollmaterial',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.RemoveField(
            model_name='pollmaterial',
            name='material',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='PostMaterial',
        ),
        migrations.DeleteModel(
            name='SiteProfile',
        ),
        migrations.DeleteModel(
            name='TextMaterial',
        ),
    ]
