# Generated by Django 2.0.3 on 2018-03-31 19:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cms', '0003_auto_20180331_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollMaterial',
            new_name='Poll',
        ),
    ]
