# Generated by Django 2.0.3 on 2018-04-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20180331_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seopage',
            options={'verbose_name': '`SEO Страница', 'verbose_name_plural': 'SEO Страницы'},
        ),
    ]
